global:
    message: Welcome to microservices Enviroment
logging:
   level:
      root: info
management:
   endpoint:
      web:
      exposure:
          include: health,info,refresh
   endpoint:
      health:
       show-details: always
