global:
   message: welcome to costomer prod enviroment
messsage: hello from prod
server:
   port: 8083
spring:
   datasource:
       url: jdbc:mysql://localhost:3306/cust_prod
       username: root
       password: root
   jpa:
     hibernate:
      ddl-auto: update
    show-sql: true
