global:
   message: welcome to order prod enviroment
messsage: hello from order prod
server:
   port: 8085
spring:
   datasource:
       url: jdbc:mysql://localhost:3306/order_prod
       username: root
       password: root
   jpa:
     hibernate:
      ddl-auto: update
    show-sql: true
